# this sucks
baseURL = "http://example.org/"
# baseURL = "/" n
# baseURL = "" no
# baseURL = "http://botnoise.org/~hipe/dtf/"

languageCode = "en-us"
title = "DTF Regulations"
description = "never see this xyzzy:001122"
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Nate Day"
    description = "You have violated The Ordnung"
    logo = "favicon/android-chrome-192x192.png"
    twitterAuthor = "@natedayta"
    githubUsername = "nathancday"
    accent = "#386890" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Roboto" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/articles/"
    name = "Articles"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

# [[menu.icon]]
#     url = "mailto:nathancday@gmail.com"
#     name = "envelope-o"
#     weight = 1
#
[[menu.icon]]
    url = "https://github.com/hipe/dtf-articles"
    name = "github"
    weight = 2
#
# [[menu.icon]]
#     url = "https://twitter.com/natedayta/"
#     name = "twitter"
#     weight = 3
#
# [[menu.icon]]
#     url = "https://www.linkedin.com/in/nathan-day-59b48435/"
#     name = "linkedin"
#     weight = 4
#
# [[menu.icon]]
#     url = "https://www.stackoverflow.com/users/5878751/nate"
#     name = "stack-overflow"
#     weight = 5
